
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import SidebarCollaspe from "@/components/Sidebar";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="flex flex-col ">

          <Header />
          <div className="flex w-100">
            <div className=" flex w-1/10">
            <SidebarCollaspe />
            </div>
            <div className="flex-col flex-1">
              {children}
            </div>
          </div>
     
        </div>
      </body>
    </html>
  );
}
