
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import SidebarCollaspe from "@/components/Sidebar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className="">
        
        <div className="flex flex-col  w-full  sm:w-[calc(134%)]">
        <Header />

          <div className="flex w-100">
           
            <div className=" flex w-1/10">
              <SidebarCollaspe />
            </div>
            <div className="flex-col flex-1">
              {children}
            </div>
          </div>

        </div>
      </body>
    </html>
  );
}
